#ifndef WS_OS_OS_THREAD_PRIORITY_H
#define WS_OS_OS_THREAD_PRIORITY_H

// OS_THREAD_PRIORITY — the ws-engine's platform-independent thread priority levels;
// osSetThreadPriority maps them onto Win32 THREAD_PRIORITY_* values.
enum OS_THREAD_PRIORITY
{
    OS_THREAD_PRIORITY_IDLE = 0,
    OS_THREAD_PRIORITY_LOWEST = 1,
    OS_THREAD_PRIORITY_BELOW_NORMAL = 2,
    OS_THREAD_PRIORITY_NORMAL = 3,
    OS_THREAD_PRIORITY_ABOVE_NORMAL = 4,
    OS_THREAD_PRIORITY_HIGHEST = 5,
    OS_THREAD_PRIORITY_TIME_CRITICAL = 6,
};

#endif // WS_OS_OS_THREAD_PRIORITY_H

// OS_THREAD_PRIORITY: DB-verified via types_enum_values $B2273293A00E2B473422E28EF5867B52
