#pragma once
/* ai_communication_type — the event vocabulary dispatched through ai_communication_event
 * (first parameter; indexes global_communication_table_indices / global_dialogue_table).
 * Source: DB types_enum_values _5770EC1170B1107620F538D7642DA181. */

enum ai_communication_type {
	_ai_communication_death = 0,
	_ai_communication_killing_spree = 1,
	_ai_communication_hurt = 2,
	_ai_communication_damage = 3,
	_ai_communication_sighted_enemy = 4,
	_ai_communication_found_enemy = 5,
	_ai_communication_unexpected_enemy = 6,
	_ai_communication_found_dead_friend = 7,
	_ai_communication_allegiance_changed = 8,
	_ai_communication_grenade_throwing = 9,
	_ai_communication_grenade_startle = 10,
	_ai_communication_grenade_sighted = 11,
	_ai_communication_grenade_danger = 12,
	_ai_communication_lost_contact = 13,
	_ai_communication_blocked = 14,
	_ai_communication_alert_noncombat = 15,
	_ai_communication_search_start = 16,
	_ai_communication_search_query = 17,
	_ai_communication_search_report = 18,
	_ai_communication_search_abandon = 19,
	_ai_communication_search_group_abandon = 20,
	_ai_communication_uncover_start = 21,
	_ai_communication_advance = 22,
	_ai_communication_retreat = 23,
	_ai_communication_cover = 24,
	_ai_communication_sighted_friend_player = 25,
	_ai_communication_shooting = 26,
	_ai_communication_shooting_vehicle = 27,
	_ai_communication_shooting_berserk = 28,
	_ai_communication_shooting_group = 29,
	_ai_communication_shooting_traitor = 30,
	_ai_communication_flee = 31,
	_ai_communication_flee_leader_died = 32,
	_ai_communication_flee_idle = 33,
	_ai_communication_attempted_flee = 34,
	_ai_communication_hiding_finished = 35,
	_ai_communication_vehicle_entry = 36,
	_ai_communication_vehicle_exit = 37,
	_ai_communication_vehicle_woohoo = 38,
	_ai_communication_vehicle_scared = 39,
	_ai_communication_vehicle_falling = 40,
	_ai_communication_surprise = 41,
	_ai_communication_berserk = 42,
	_ai_communication_melee = 43,
	_ai_communication_dive = 44,
	_ai_communication_uncover_exclamation = 45,
	_ai_communication_falling_to_death = 46,
	_ai_communication_leap = 47,
	_ai_communication_postcombat_alone = 48,
	_ai_communication_postcombat_unscathed = 49,
	_ai_communication_postcombat_wounded = 50,
	_ai_communication_postcombat_massacre = 51,
	_ai_communication_postcombat_triumph = 52,
	_ai_communication_postcombat_check_enemy = 53,
	_ai_communication_postcombat_check_friend = 54,
	_ai_communication_postcombat_shoot_corpse = 55,
	_ai_communication_postcombat_celebrate = 56,
	NUMBER_OF_AI_COMMUNICATION_TYPES = 57,
};

// ai_communication_type: DB-verified via types_enum_values _5770EC1170B1107620F538D7642DA181 (anonymous compiled enum)
