#ifndef BLAM_DATA_GLOBALS_H
#define BLAM_DATA_GLOBALS_H
/* AUTO-GENERATED by tools/gen_canonical_globals_header.py — do not hand-edit.
 * Canonical extern for every Blam data-segment global, lifted verbatim from the
 * verified src/data/<sym>.c storage definitions (the single source of truth).
 * Include this and drop inline externs so type divergence becomes a compile error. */

#include "ID3DXEffectPool.h"
#include "_D3DCAPS9.h"
#include "_D3DXMACRO.h"
#include "_LARGE_INTEGER.h"
#include "_field_type_translated_index_parameters.h"
#include "achievements_info.h"
#include "advertised_game_data.h"
#include "ai_globals.h"
#include "animation_event_header.h"
#include "animation_event_v1.h"
#include "animation_playback.h"
#include "animation_playback_controller.h"
#include "bitmap_data.h"
#include "breakable_surface_globals.h"
#include "bsp3d.h"
#include "build_sprite_globals.h"
#include "buildin_multiplayer_map_s.h"
#include "byte_swap_definition.h"
#include "cache_file_globals.h"
#include "cache_file_tag_instance.h"
#include "cached_player_profile.h"
#include "cached_variant_profile.h"
#include "camera_control.h"
#include "camera_script_globals.h"
#include "cheats.h"
#include "chicago_pixel_shader.h"
#include "chicago_shaders.h"
#include "cinematic_globals_definition.h"
#include "cinematic_screen_effect_globals.h"
#include "cluster_partition.h"
#include "collision_bsp.h"
#include "collision_feature_list.h"
#include "console_globals.h"
#include "convex_polygon2d.h"
#include "ctf_globals.h"
#include "d3d_boundary.h"
#include "damage_material.h"
#include "data_array.h"
#include "data_file_s.h"
#include "data_packet_group_definition.h"
#include "data_packet_group_packet.h"
#include "decal_globals.h"
#include "detail_object_global_runtime_data.h"
#include "dialogue_event_status.h"
#include "director.h"
#include "draw_character_software_globals.h"
#include "dynamic_array.h"
#include "dynamic_screen_vertex.h"
#include "dynamic_unlit_vertex.h"
#include "dynamic_vertices.h"
#include "editor_camera_focus_t.h"
#include "effect_marker_list.h"
#include "error_global_data.h"
#include "event_manager_globals.h"
#include "exposed_parameter.h"
#include "fg_graph.h"
#include "field_properties_definition.h"
#include "field_type_definition.h"
#include "find_files_globals.h"
#include "firing_position.h"
#include "first_person_weapon.h"
#include "flying_camera.h"
#include "font_drawing_globals.h"
#include "game_engine.h"
#include "game_engine_globals.h"
#include "game_engine_playlist_s.h"
#include "game_globals.h"
#include "game_globals_rasterizer_data.h"
#include "game_globals_tag.h"
#include "game_looping_sound_data.h"
#include "game_sound_globals.h"
#include "game_state_globals.h"
#include "game_statistics_globals.h"
#include "game_time_globals.h"
#include "game_time_statistics.h"
#include "game_variant.h"
#include "global_frame_parameters.h"
#include "global_window_parameters.h"
#include "glow_globals.h"
#include "hardware_character_cache.h"
#include "hcex/HALO_SOUND_SYSTEM_fwd.h"
#include "headers/_D3DDEVTYPE.h"
#include "headers/debug_key.h"
#include "headers/director_variable_definition.h"
#include "headers/event_record.h"
#include "headers/metrics_globals.h"
#include "headers/real_argb_color.h"
#include "headers/real_rectangle3d.h"
#include "headers/real_rgb_color.h"
#include "headers/real_vector2d.h"
#include "headers/unit_control_data_entry.h"
#include "headers/widget_instance.h"
#include "hs_compile_globals.h"
#include "hs_function_definition.h"
#include "hs_global_external.h"
#include "hs_type.h"
#include "hud_globals.h"
#include "hud_messaging_globals.h"
#include "hud_messaging_parameters_definition.h"
#include "hud_nav_point_player_datum.h"
#include "hud_scripted_globals.h"
#include "input_abstraction_globals.h"
#include "input_globals_xbox.h"
#include "king_globals.h"
#include "leaf_map_globals.h"
#include "light_volume_frame.h"
#include "lights_globals.h"
#include "lruv_cache.h"
#include "main_globals.h"
#include "memory_pool.h"
#include "message_delta_encoding_class.h"
#include "motion_sensor_globals_definition.h"
#include "multiplayer_map_s.h"
#include "mutex.h"
#include "net_graph.h"
#include "netgame_goal.h"
#include "network_game_server.h"
#include "object_globals.h"
#include "object_type_definition.h"
#include "observer_command.h"
#include "observer_globals.h"
#include "oddball_globals.h"
#include "pc_sound_cache_globals.h"
#include "pc_texture_cache_globals.h"
#include "persistant_game_data_info.h"
#include "persisted_camera.h"
#include "physical_memory_map_globals.h"
#include "platform_sound_channel_properties.h"
#include "platform_sound_manager_definition.h"
#include "platoon_datum.h"
#include "play_stage.h"
#include "player_control_globals.h"
#include "player_effect_globals_definition.h"
#include "player_profile_globals.h"
#include "player_score_baseline_slot.h"
#include "player_ui_globals.h"
#include "players_global_data.h"
#include "playlist_profile_globals.h"
#include "point2d.h"
#include "projectile_material_response_definition.h"
#include "queued_mp_sound.h"
#include "race_globals.h"
#include "random_math_globals.h"
#include "rasterizer_debug_options.h"
#include "rasterizer_draw_pipeline.h"
#include "rasterizer_dx9_shader_table.h"
#include "rasterizer_engine_globals.h"
#include "rasterizer_frame_statistics_s.h"
#include "rasterizer_globals.h"
#include "rasterizer_lens_flare_submit_parameters.h"
#include "rasterizer_lights.h"
#include "rasterizer_model_begin_parameters.h"
#include "rasterizer_model_techniques.h"
#include "rasterizer_render_target.h"
#include "real_argb_color.h"
#include "real_euler_angles2d.h"
#include "real_matrix4x3.h"
#include "real_plane3d.h"
#include "real_point2d.h"
#include "real_point3d.h"
#include "real_quaternion.h"
#include "real_rectangle2d.h"
#include "real_rgb_color.h"
#include "real_vector2d.h"
#include "real_vector3d.h"
#include "render_globals.h"
#include "render_lighting.h"
#include "render_model_effect.h"
#include "render_object_globals.h"
#include "render_screen_flash_type.h"
#include "render_sky_globals.h"
#include "render_window.h"
#include "saved_film.h"
#include "saved_game_files_globals.h"
#include "scenario.h"
#include "scenario_globals.h"
#include "shader_effect.h"
#include "simple_decompressor_definition.h"
#include "single_player_level_data.h"
#include "slayer_globals.h"
#include "sound_channel_datum.h"
#include "sound_class_datum.h"
#include "sound_class_definition.h"
#include "sound_manager_globals_t.h"
#include "sound_preferences.h"
#include "squad_datum.h"
#include "stack_memory_pool.h"
#include "stack_walk_globals.h"
#include "struct_game_allegiance_globals.h"
#include "structure_bsp.h"
#include "structure_decals_globals_definition.h"
#include "structure_render_globals.h"
#include "structure_visibility_globals.h"
#include "super_remote_players_action_update.h"
#include "terminal_globals.h"
#include "text_bounds_globals.h"
#include "text_pick_globals.h"
#include "thread.h"
#include "transparent_geometry_group.h"
#include "ui_widget_replace_function.h"
#include "unit_control_data.h"
#include "unit_control_data_entry.h"
#include "unit_globals.h"
#include "unit_hud_globals_definition.h"
#include "update_client_globals.h"
#include "update_server_globals.h"
#include "vector_avoidance_ray.h"
#include "vehicle_remapper_s.h"
#include "vertex_shader_declaration.h"
#include "vertex_shader_function.h"
#include "vibrate_globals.h"
#include "video_resolution_s.h"
#include "virtual_keyboard_globals_t.h"
#include "weapon_hud_globals_definition.h"
#include "weather_particle_system_globals.h"
#include "widget_batch.h"
#include "widget_globals.h"
#include "widget_instance.h"
#include "widget_state.h"
#include "widget_type_definition.h"

extern char *AppendText;
extern int EnabledScreenShot;
extern unsigned char InsideScene;
extern int UsingD3DSpy;
extern short keyboard_auxbutton_mapping[3];
extern stack_memory_pool_medium _medium_widget_memory_pool;
extern unsigned __int8 _test_no_more_active_camo;
extern const unsigned __int16 _translation_table[108];
extern const unsigned __int16 _translation_table_0[108];
extern unsigned char accept_remote_connections;
extern data_array *actor_data;
extern void (*after_load_procs[15])(void);
extern hs_global_external ai_debug_ballistic_lineoffire_freeze_definition;
extern hs_global_external ai_debug_blind_definition;
extern hs_global_external ai_debug_communication_focus_enable_definition;
extern hs_global_external ai_debug_communication_random_disabled_definition;
extern hs_global_external ai_debug_communication_timeout_disabled_definition;
extern hs_global_external ai_debug_communication_unit_repeat_disabled_definition;
extern hs_global_external ai_debug_deaf_definition;
extern hs_global_external ai_debug_disable_wounded_sounds_definition;
extern hs_global_external ai_debug_evaluate_all_positions_definition;
extern hs_global_external ai_debug_fast_los_definition;
extern hs_global_external ai_debug_flee_always_definition;
extern hs_global_external ai_debug_force_all_active_definition;
extern hs_global_external ai_debug_force_crouch_definition;
extern hs_global_external ai_debug_force_vocalizations_definition;
extern hs_global_external ai_debug_ignore_player_definition;
extern hs_global_external ai_debug_invisible_player_definition;
extern hs_global_external ai_debug_oversteer_disable_definition;
extern hs_global_external ai_debug_path_accept_radius_definition;
extern hs_global_external ai_debug_path_attractor_definition;
extern hs_global_external ai_debug_path_attractor_radius_definition;
extern hs_global_external ai_debug_path_attractor_weight_definition;
extern hs_global_external ai_debug_path_definition;
extern hs_global_external ai_debug_path_disable_obstacle_avoidance_definition;
extern hs_global_external ai_debug_path_disable_smoothing_definition;
extern hs_global_external ai_debug_path_end_freeze_definition;
extern hs_global_external ai_debug_path_flood_definition;
extern hs_global_external ai_debug_path_maximum_radius_definition;
extern hs_global_external ai_debug_path_start_freeze_definition;
extern hs_global_external ai_fix_actor_variants_definition;
extern hs_global_external ai_fix_defending_guard_firing_positions_definition;
extern ai_globals_t * ai_globals;
extern hs_global_external ai_print_acknowledgement_definition;
extern hs_global_external ai_print_allegiance_definition;
extern hs_global_external ai_print_automatic_migration_definition;
extern hs_global_external ai_print_bsp_transition_definition;
extern hs_global_external ai_print_command_lists_definition;
extern hs_global_external ai_print_communication_definition;
extern hs_global_external ai_print_communication_player_definition;
extern hs_global_external ai_print_conversations_definition;
extern hs_global_external ai_print_damage_modifiers_definition;
extern hs_global_external ai_print_evaluation_statistics_definition;
extern hs_global_external ai_print_killing_sprees_definition;
extern hs_global_external ai_print_lost_speech_definition;
extern hs_global_external ai_print_major_upgrade_definition;
extern hs_global_external ai_print_migration_definition;
extern hs_global_external ai_print_oversteer_definition;
extern hs_global_external ai_print_placement_definition;
extern hs_global_external ai_print_pursuit_checks_definition;
extern hs_global_external ai_print_respawn_definition;
extern hs_global_external ai_print_rule_values_definition;
extern hs_global_external ai_print_rules_definition;
extern hs_global_external ai_print_scripting_definition;
extern hs_global_external ai_print_secondary_looking_definition;
extern hs_global_external ai_print_speech_definition;
extern hs_global_external ai_print_speech_timers_definition;
extern hs_global_external ai_print_surprise_definition;
extern hs_global_external ai_print_uncovering_definition;
extern hs_global_external ai_print_unfinished_paths_definition;
extern hs_global_external ai_print_vocalizations_definition;
extern hs_global_external ai_profile_disable_definition;
extern hs_global_external ai_profile_random_definition;
extern hs_global_external ai_render_activation_definition;
extern hs_global_external ai_render_active_cover_seeking_definition;
extern hs_global_external ai_render_aiming_validity_definition;
extern hs_global_external ai_render_aiming_vectors_definition;
extern hs_global_external ai_render_all_actors_definition;
extern hs_global_external ai_render_audibility_definition;
extern hs_global_external ai_render_ballistic_lineoffire_definition;
extern hs_global_external ai_render_burst_geometry_definition;
extern hs_global_external ai_render_charge_decisions_definition;
extern hs_global_external ai_render_control_definition;
extern hs_global_external ai_render_current_state_definition;
extern hs_global_external ai_render_danger_zones_definition;
extern hs_global_external ai_render_definition;
extern hs_global_external ai_render_detailed_state_definition;
extern hs_global_external ai_render_dialogue_variants_definition;
extern hs_global_external ai_render_emotions_definition;
extern hs_global_external ai_render_encounter_activeregion_definition;
extern hs_global_external ai_render_evaluations_definition;
extern hs_global_external ai_render_firing_positions_definition;
extern hs_global_external ai_render_grenade_decisions_definition;
extern hs_global_external ai_render_gun_positions_definition;
extern hs_global_external ai_render_idle_look_definition;
extern hs_global_external ai_render_inactive_actors_definition;
extern hs_global_external ai_render_lineoffire_crouching_definition;
extern hs_global_external ai_render_lineoffire_definition;
extern hs_global_external ai_render_lineofsight_definition;
extern hs_global_external ai_render_melee_check_definition;
extern hs_global_external ai_render_paths_avoidance_obstacles_definition;
extern hs_global_external ai_render_paths_avoidance_search_definition;
extern hs_global_external ai_render_paths_avoidance_segment_definition;
extern hs_global_external ai_render_paths_avoided_definition;
extern hs_global_external ai_render_paths_current_definition;
extern hs_global_external ai_render_paths_definition;
extern hs_global_external ai_render_paths_destination_definition;
extern hs_global_external ai_render_paths_failed_definition;
extern hs_global_external ai_render_paths_nodes_all_definition;
extern hs_global_external ai_render_paths_nodes_closest_definition;
extern hs_global_external ai_render_paths_nodes_costs_definition;
extern hs_global_external ai_render_paths_nodes_definition;
extern hs_global_external ai_render_paths_nodes_polygons_definition;
extern hs_global_external ai_render_paths_raw_definition;
extern hs_global_external ai_render_paths_selected_only_definition;
extern hs_global_external ai_render_paths_smoothed_definition;
extern hs_global_external ai_render_player_aiming_blocked_definition;
extern hs_global_external ai_render_player_ratings_definition;
extern hs_global_external ai_render_postcombat_definition;
extern hs_global_external ai_render_projectile_aiming_definition;
extern hs_global_external ai_render_props_definition;
extern hs_global_external ai_render_props_no_friends_definition;
extern hs_global_external ai_render_props_target_weight_definition;
extern hs_global_external ai_render_props_unopposable_definition;
extern hs_global_external ai_render_props_unreachable_definition;
extern hs_global_external ai_render_props_web_definition;
extern hs_global_external ai_render_pursuit_definition;
extern hs_global_external ai_render_recent_damage_definition;
extern hs_global_external ai_render_secondary_looking_definition;
extern hs_global_external ai_render_shooting_definition;
extern hs_global_external ai_render_spatial_effects_definition;
extern hs_global_external ai_render_speech_definition;
extern hs_global_external ai_render_states_definition;
extern hs_global_external ai_render_support_surfaces_definition;
extern hs_global_external ai_render_targets_definition;
extern hs_global_external ai_render_targets_last_visible_definition;
extern hs_global_external ai_render_teams_definition;
extern hs_global_external ai_render_threats_definition;
extern hs_global_external ai_render_trigger_definition;
extern hs_global_external ai_render_vector_avoidance_avoid_t_definition;
extern hs_global_external ai_render_vector_avoidance_clear_time_definition;
extern hs_global_external ai_render_vector_avoidance_definition;
extern hs_global_external ai_render_vector_avoidance_intermediate_definition;
extern hs_global_external ai_render_vector_avoidance_objects_definition;
extern hs_global_external ai_render_vector_avoidance_rays_definition;
extern hs_global_external ai_render_vector_avoidance_sense_t_definition;
extern hs_global_external ai_render_vector_avoidance_weights_definition;
extern hs_global_external ai_render_vehicle_avoidance_definition;
extern hs_global_external ai_render_vehicles_enterable_definition;
extern hs_global_external ai_render_vision_cones_definition;
extern hs_global_external ai_render_vitality_definition;
extern hs_global_external ai_show_actors_definition;
extern hs_global_external ai_show_definition;
extern hs_global_external ai_show_line_of_sight_definition;
extern hs_global_external ai_show_paths_definition;
extern hs_global_external ai_show_prop_types_definition;
extern hs_global_external ai_show_sound_distance_definition;
extern hs_global_external ai_show_stats_definition;
extern hs_global_external ai_show_swarms_definition;
extern byte_swap_definition aiming_speed_event_data_bs_definition;
extern byte_swap_definition aiming_speed_set_event_v1_bs_definition;
extern unsigned char allow_client_side_weapon_projectiles;
extern hs_global_external allow_client_side_weapon_projectiles_definition;
extern hs_global_external allow_out_of_sync_definition;
extern float alpha;
extern float alpha_0;
extern float alpha_1;
extern char *alternative_directories[6];
extern unsigned char always_filter_hud;
extern byte_swap_definition angle_vector_set_event_v1_bs_definition;
extern byte_swap_definition animation_event_v1_bs_definition;
extern byte_swap_definition animation_state_event_data_bs_definition;
extern byte_swap_definition animation_state_set_event_v1_bs_definition;
extern data_array *animation_threads;
extern data_array *antenna_data;
extern void (*apply_funcs[23])(unit_control_data *, const animation_event_v1 *, const char **);
extern void (*apply_funcs_0[23])(animation_playback_controller *, unit_control_data *, const animation_event_header *, const char **);
extern __int16 assertion_count;
extern unsigned int attract_mode_countdown_timer;
extern unsigned char attract_mode_immediate_start;
extern real_vector3d avoidance_directions[8];
extern vector_avoidance_ray avoidance_rays[8][2];
extern unsigned int ay;
extern unsigned int az;
extern dynamic_array banned_players;
extern const char *base_seat_labels[6];
extern void (*before_load_procs[1])(void);
extern void (*before_save_procs[1])(void);
extern object_type_definition biped_data_definition;
extern int biped_incremental_rate;
extern hs_global_external biped_incremental_rate_definition;
extern const char *bitmap_format_string_table[19];
extern const char *bitmap_type_string_table[5];
extern __int16 blip_player_index;
extern int blocked_message_delay;
extern float blue;
extern float blue_0;
extern float blue_1;
extern char *blurred_permutation_names[2];
extern unsigned char breakable_surface_effect_enabled;
extern hs_global_external breakable_surfaces_definition;
extern wchar_t build_number_string[64];
extern build_sprite_globals_data build_sprite_globals;
extern buildin_multiplayer_map_s builtin_multiplayer_maps[19];
extern unsigned char button_mappings[14];
extern const unsigned char button_mappings_0[14];
extern cache_file_globals_s cache_file_globals_0;
extern char cache_root_directory[256];
extern data_array *cached_object_render_states;
extern _cached_player_profile cached_player_profile[3];
extern _cached_variant_profile cached_variant_profile[3];
extern float cam_ofs;
extern short camera_mode;
extern camera_script_globals_t camera_script_globals;
extern real_point2d center_point;
extern float cf_DecalSlopeZBiasValue;
extern float cf_DecalZBiasValue;
extern unsigned int cf_ForceShader;
extern unsigned int cf_LinearTextureAddressingSun;
extern unsigned int cf_LinearTextureAddressingZoom;
extern unsigned int cf_MinMaxBlendOpIsBroken;
extern unsigned int cf_SafeMode;
extern unsigned int cf_UseAlternateConvolveMask;
extern void (*channel_set_properties)(short, platform_sound_channel_properties *, unsigned char, short);
extern cheat_globals cheat;
extern hs_global_external cheat_bottomless_clip_definition;
extern hs_global_external cheat_bump_possession_definition;
extern hs_global_external cheat_controller_definition;
extern hs_global_external cheat_deathless_player_definition;
extern hs_global_external cheat_infinite_ammo_definition;
extern hs_global_external cheat_jetpack_definition;
extern hs_global_external cheat_medusa_definition;
extern hs_global_external cheat_omnipotent_definition;
extern hs_global_external cheat_reflexive_damage_effects_definition;
extern hs_global_external cheat_super_jump_definition;
extern chicago_pixel_shader chicago_shader_table[1014];
extern int chicago_shader_table_size;
extern cinematic_globals_definition *cinematic_globals;
extern struct cinematic_screen_effect_globals *cinematic_screen_effect_globals;
extern int client_log_destination;
extern hs_global_external client_log_destination_definition;
extern cluster_partition collideable_object_cluster_partition;
extern hs_global_external collision_debug_definition;
extern hs_global_external collision_debug_features_definition;
extern hs_global_external collision_debug_flag_back_facing_surfaces_definition;
extern hs_global_external collision_debug_flag_front_facing_surfaces_definition;
extern hs_global_external collision_debug_flag_ignore_breakable_surfaces_definition;
extern hs_global_external collision_debug_flag_ignore_invisible_surfaces_definition;
extern hs_global_external collision_debug_flag_ignore_two_sided_surfaces_definition;
extern hs_global_external collision_debug_flag_media_definition;
extern hs_global_external collision_debug_flag_objects_bipeds_definition;
extern hs_global_external collision_debug_flag_objects_controls_definition;
extern hs_global_external collision_debug_flag_objects_definition;
extern hs_global_external collision_debug_flag_objects_equipment_definition;
extern hs_global_external collision_debug_flag_objects_light_fixtures_definition;
extern hs_global_external collision_debug_flag_objects_machines_definition;
extern hs_global_external collision_debug_flag_objects_placeholders_definition;
extern hs_global_external collision_debug_flag_objects_projectiles_definition;
extern hs_global_external collision_debug_flag_objects_scenery_definition;
extern hs_global_external collision_debug_flag_objects_vehicles_definition;
extern hs_global_external collision_debug_flag_objects_weapons_definition;
extern hs_global_external collision_debug_flag_skip_passthrough_bipeds_definition;
extern hs_global_external collision_debug_flag_structure_definition;
extern hs_global_external collision_debug_flag_try_to_keep_location_valid_definition;
extern hs_global_external collision_debug_flag_use_vehicle_physics_definition;
extern hs_global_external collision_debug_height_definition;
extern hs_global_external collision_debug_length_definition;
extern hs_global_external collision_debug_phantom_bsp_definition;
extern hs_global_external collision_debug_point_x_definition;
extern hs_global_external collision_debug_point_y_definition;
extern hs_global_external collision_debug_point_z_definition;
extern hs_global_external collision_debug_repeat_definition;
extern hs_global_external collision_debug_spray_definition;
extern hs_global_external collision_debug_vector_i_definition;
extern hs_global_external collision_debug_vector_j_definition;
extern hs_global_external collision_debug_vector_k_definition;
extern hs_global_external collision_debug_width_definition;
extern hs_global_external collision_log_detailed_definition;
extern hs_global_external collision_log_extended_definition;
extern hs_global_external collision_log_render_definition;
extern hs_global_external collision_log_time_definition;
extern hs_global_external collision_log_totals_only_definition;
extern unsigned int combined_pas[16];
extern real_argb_color console_color;
extern unsigned char console_dump_to_file;
extern hs_global_external console_dump_to_file_definition;
extern console_globals_t console_globals;
extern data_array *contrail_data;
extern data_array *contrail_point_data;
extern object_type_definition control_data_definition;
extern byte_swap_definition control_flags_event_data_bs_definition;
extern byte_swap_definition control_flags_set_event_v1_bs_definition;
extern unsigned __int8 controls_enable_crouch;
extern hs_global_external controls_enable_crouch_definition;
extern unsigned __int8 controls_enable_doubled_spin;
extern hs_global_external controls_enable_doubled_spin_definition;
extern unsigned __int8 controls_swap_doubled_spin_state;
extern hs_global_external controls_swap_doubled_spin_state_definition;
extern unsigned char controls_swapped;
extern hs_global_external controls_swapped_definition;
extern data_array * conversation_data;
extern unsigned char coop_mode_selected;
extern unsigned int crc_table_1[256];
extern unsigned __int8 crc_table_built;
extern int credits_endgame_mode;
extern unsigned int credits_last_update_time;
extern dynamic_array credits_list;
extern float crosshairOffsetX;
extern struct game_engine ctf_engine;
extern ctf_globals_type ctf_globals;
extern ctf_globals_type ctf_globals_baseline;
extern animation_playback current_playback;
extern const char *data_file_dir;
extern const char *data_file_dir_default;
extern int data_file_reorder_on_write;
extern int debounce_f11;
extern int debounce_f12;
extern hs_global_external debug_bink_definition;
extern hs_global_external debug_biped_limp_body_disable_definition;
extern hs_global_external debug_biped_physics_definition;
extern hs_global_external debug_biped_skip_collision_definition;
extern hs_global_external debug_biped_skip_update_definition;
extern hs_global_external debug_bsp_definition;
extern hs_global_external debug_camera_definition;
extern hs_global_external debug_collision_skip_objects_definition;
extern hs_global_external debug_collision_skip_vectors_definition;
extern hs_global_external debug_damage_definition;
extern hs_global_external debug_damage_taken_definition;
extern hs_global_external debug_decals_definition;
extern unsigned __int8 debug_detail_objects;
extern hs_global_external debug_detail_objects_definition;
extern hs_global_external debug_effects_nonviolent_definition;
extern unsigned char debug_fog_planes;
extern hs_global_external debug_fog_planes_definition;
extern unsigned __int8 debug_force_frame_rate_update;
extern unsigned char debug_frame_rate;
extern hs_global_external debug_framerate_definition;
extern hs_global_external debug_frustum_definition;
extern unsigned char debug_game_save;
extern hs_global_external debug_game_save_definition;
extern hs_global_external debug_inactive_objects_definition;
extern hs_global_external debug_input_definition;
extern hs_global_external debug_input_target_definition;
extern int debug_leaf_index;
extern hs_global_external debug_leaf_index_definition;
extern int debug_leaf_portal_index;
extern hs_global_external debug_leaf_portal_index_definition;
extern unsigned char debug_leaf_portals;
extern hs_global_external debug_leaf_portals_definition;
extern hs_global_external debug_lights_definition;
extern unsigned char debug_looping_sound;
extern hs_global_external debug_looping_sound_definition;
extern hs_global_external debug_material_effects_definition;
extern unsigned char debug_motion_sensor_draw_all_units;
extern hs_global_external debug_motion_sensor_draw_all_units_definition;
extern unsigned char debug_no_drawing;
extern hs_global_external debug_no_drawing_definition;
extern unsigned __int8 debug_no_frustum_clip;
extern hs_global_external debug_no_frustum_clip_definition;
extern hs_global_external debug_object_garbage_collection_definition;
extern int debug_object_index;
extern hs_global_external debug_object_lights_definition;
extern unsigned char debug_objects;
extern hs_global_external debug_objects_biped_autoaim_pills_definition;
extern hs_global_external debug_objects_biped_messages_definition;
extern hs_global_external debug_objects_biped_physics_pills_definition;
extern hs_global_external debug_objects_bounding_spheres_definition;
extern hs_global_external debug_objects_collision_models_definition;
extern hs_global_external debug_objects_definition;
extern hs_global_external debug_objects_devices_definition;
extern hs_global_external debug_objects_equipment_messages_definition;
extern hs_global_external debug_objects_names_definition;
extern hs_global_external debug_objects_pathfinding_spheres_definition;
extern hs_global_external debug_objects_physics_definition;
extern hs_global_external debug_objects_position_velocity_definition;
extern hs_global_external debug_objects_projectile_messages_definition;
extern hs_global_external debug_objects_root_node_definition;
extern hs_global_external debug_objects_unit_mouth_apeture_definition;
extern hs_global_external debug_objects_unit_seats_definition;
extern hs_global_external debug_objects_unit_vectors_definition;
extern hs_global_external debug_objects_vehicle_messages_definition;
extern hs_global_external debug_objects_vehicle_powered_mass_points_definition;
extern hs_global_external debug_objects_weapon_messages_definition;
extern hs_global_external debug_obstacle_path_definition;
extern hs_global_external debug_obstacle_path_goal_point_x_definition;
extern hs_global_external debug_obstacle_path_goal_point_y_definition;
extern hs_global_external debug_obstacle_path_goal_surface_index_definition;
extern hs_global_external debug_obstacle_path_on_failure_definition;
extern hs_global_external debug_obstacle_path_start_point_x_definition;
extern hs_global_external debug_obstacle_path_start_point_y_definition;
extern hs_global_external debug_obstacle_path_start_surface_index_definition;
extern int debug_off_aiming_object_index;
extern int debug_off_interpolating_object_index;
extern int debug_off_looking_object_index;
extern hs_global_external debug_permanent_decals_definition;
extern unsigned char debug_physics_disable_penetration_freeze;
extern hs_global_external debug_physics_disable_penetration_freeze_definition;
extern hs_global_external debug_player_color_definition;
extern hs_global_external debug_player_definition;
extern hs_global_external debug_player_teleport_definition;
extern hs_global_external debug_point_physics_definition;
extern unsigned char debug_portals;
extern hs_global_external debug_portals_definition;
extern __int16 debug_rasterizer_light_count;
extern hs_global_external debug_recording_definition;
extern hs_global_external debug_recording_newlines_definition;
extern int debug_render_freeze;
extern hs_global_external debug_render_freeze_definition;
extern int debug_score;
extern hs_global_external debug_score_definition;
extern unsigned char debug_scripting;
extern hs_global_external debug_scripting_definition;
extern unsigned __int8 debug_sound;
extern unsigned char debug_sound_cache;
extern unsigned char debug_sound_cache_graph;
extern unsigned char debug_sound_channels;
extern hs_global_external debug_sound_channels_definition;
extern unsigned char debug_sound_channels_detail;
extern hs_global_external debug_sound_channels_detail_definition;
extern hs_global_external debug_sound_definition;
extern hs_global_external debug_sound_environment_definition;
extern unsigned char debug_sound_hardware;
extern hs_global_external debug_sound_hardware_definition;
extern unsigned char debug_sprites;
extern hs_global_external debug_sprites_definition;
extern hs_global_external debug_structure_definition;
extern hs_global_external debug_texture_cache_definition;
extern unsigned char debug_trigger_volumes;
extern hs_global_external debug_trigger_volumes_definition;
extern hs_global_external debug_unit_all_animations_definition;
extern hs_global_external debug_unit_animations_definition;
extern hs_global_external debug_unit_illumination_definition;
extern struct decal_globals *decal_globals;
extern real_point2d decal_points2d_temp[2][12];
extern D3DPixelShader *decal_shader;
extern hs_global_external decals_definition;
extern unsigned char decals_enabled;
extern simple_decompressor_definition decompress_globals;
extern damage_material default_damage_material;
extern const convex_polygon2d default_face;
extern float default_function_values[4];
extern projectile_material_response_definition default_projectile_material_response;
extern real_rgb_color default_render_model_change_colors;               /* @0x844A5928 (r22/change_colors NULL default; ex "function_colors") */
extern render_model_effect default_render_model_effect;
extern char default_render_model_region_permutation_indices[32];        /* @0x844A5908 (r20/region_permutation_indices NULL default; ex "change_color") */
extern sound_preferences default_sound_preferences;
extern const wchar_t *default_string;
extern game_variant * (*default_variant_building_functions[])(game_variant *);
extern int delete_profile_index;
extern char delete_savegame_filename[64];
extern char *demo_scenario_0;
extern real_plane3d depths_of_hell;
extern struct detail_object_global_runtime_data *detail_object_global_runtime_data;
extern hs_global_external developer_mode_definition;
extern data_array * device_groups_data;
extern unsigned char device_is_lost;
extern struct device_usage_info_s device_usage_info;
extern point2d dimensions;
extern point2d dimensions_0;
extern point2d dimensions_1;
extern const char *director_camera_mode_names[5];
extern unsigned char *director_camera_scripted;
extern unsigned __int8 director_camera_switch_fast;
extern hs_global_external director_camera_switch_fast_definition;
extern hs_global_external director_camera_switching_definition;
extern director_globals_t director_globals;
extern void (*disconnect_from_structure_bsp_procs[10])(void);
extern unsigned char display_framerate;
extern hs_global_external display_framerate_definition;
extern wchar_t display_name[128];
extern unsigned char display_precache_progress;
extern hs_global_external display_precache_progress_definition;
extern unsigned char display_vblank_deltas;
extern hs_global_external display_vblank_deltas_definition;
extern advertised_game_data *displayed_servers[9];
extern draw_character_software_globals_t draw_character_software_globals;
extern unsigned char dropped_samples[60];
extern int dump_psh_to_binary;
extern int dump_vsh_to_binary;
extern float duration;
extern float duration_0;
extern float duration_1;
extern rasterizer_dx9_shader *dxeffect_shader;
extern dynamic_vertices_struct dynamic_vertices;
extern flying_camera *editor_camera;
extern editor_camera_focus_definition editor_camera_focus;
extern render_globals *editor_custom_render;
extern data_array * effect_data;
extern data_array *effect_location_data;
extern const char *effect_marker_names[];
extern unsigned char effects_corpse_nonviolent;
extern hs_global_external effects_corpse_nonviolent_definition;
extern data_array * encounter_data;
extern short enumeration_maximum_count;
extern real_matrix4x3 environment_shadow_projection_matrix;
extern object_type_definition equipment_data_definition;
extern int equipment_incremental_rate;
extern hs_global_external equipment_incremental_rate_definition;
extern error_global_data error_globals;
extern hs_global_external error_suppress_all_definition;
extern uint8_t (*event_handler_function_list[107])(widget_instance *widget, event_record *event, uint8_t *widget_deleted);
extern _event_manager_globals event_manager_globals;
extern float eye_distance_to_fog_plane;
extern hs_global_external f0_definition;
extern hs_global_external f1_definition;
extern hs_global_external f2_definition;
extern hs_global_external f3_definition;
extern hs_global_external f4_definition;
extern hs_global_external f5_definition;
extern int fade_function;
extern int fade_function_0;
extern int fade_function_1;
extern char faked_xbox_command_line[8];
extern collision_feature_list features;
extern int fg_frame_height;
extern int fg_frame_width;
extern fg_graph fg_graphs[1];
extern _field_properties_definition field_properties_object_index_definition;
extern _field_type_translated_index_parameters field_properties_object_index_parameters;
extern _field_properties_definition field_properties_player_index_definition;
extern _field_type_translated_index_parameters field_properties_player_index_parameters;
extern char file_location_volume_names[3][256];
extern __int16 filter_coefficients[10];
extern float final_offset;
extern unsigned __int8 find_all_fucked_up_shit;
extern hs_global_external find_all_fucked_up_shit_definition;
extern find_files_globals_t find_files_globals;
extern unsigned char first_line;
extern object_type_definition *first_object_type_definition;
extern first_person_weapon * first_person_weapons;
extern data_array *flag_data;
extern unsigned __int8 flip_status;
extern struct font_drawing_globals font_drawing_globals;
extern hs_global_external force_all_player_views_to_default_player_definition;
extern float force_alpha;
extern unsigned __int8 force_alpha_blend;
extern float forward_scale;
extern __int16 fps_sample_count;
extern light_volume_frame frame_storage;
extern hs_global_external framerate_lock_definition;
extern hs_global_external framerate_throttle_definition;
extern hs_global_external freeze_flying_camera_definition;
extern float fudge_offset;
extern unsigned char fudge_vector;
extern int gConnectionTimeoutMilliseconds;
extern unsigned char gForceServerToStop;
extern unsigned __int8 gGameEngineRunningOriginalMap;
extern net_graph gGraph;
extern int gITEM_PLACEMENT_BITS_X;
extern int gITEM_PLACEMENT_BITS_Y;
extern int gITEM_PLACEMENT_BITS_Z;
extern unsigned char gIsClientVersion;
extern int gLOCALITY_BITS_PER_COMPONENT_DELTA_INTERNET;
extern int gLOCALITY_BITS_PER_COMPONENT_FULL_INTERNET;
extern int gLOCALITY_BITS_PER_COMPONENT_FULL_LAN;
extern float gLOCALITY_DELTA_CUTOFF_DISTANCE_INTERNET;
extern float gLOCALITY_MINIMUM_MOVE_DISTANCE_INTERNET;
extern int gMapCycleTimeoutSeconds;
extern message_delta_processor_encoding_class gMessageEncodingClass;
extern unsigned __int8 gNetGraphEnabled;
extern unsigned int gNetGraphSamplePeriod;
extern int gNetMeterBandwidth;
extern const unsigned char *g_CurrentLocalNodeTable;
extern int g_CurrentLocalNodeTableSize;
extern unsigned char g_HACK_client_reconnect_attempt_in_progress;
extern unsigned char g_InsideGameTick;
extern exposed_parameter g_exposed_params[64];
extern super_remote_players_action_update g_incremental_super_remote_players_action_upate;
extern int g_last_multiplayer_hit_sound_time;
extern char g_message_encode_buffer[4096];
extern int g_num_exposed_params;
extern unsigned int g_parameters_protocol_number;
extern char g_parameters_string[2048];
extern player_score_baseline_slot g_player_score_baselines[32];
extern unsigned char g_player_score_is_initialized;
extern int g_player_score_number_of_used_slots;
extern unsigned char g_protocol_changeover_enabled;
extern unsigned __int8 g_protocol_changeover_message_flag;
extern unsigned char g_running_simulated_update;
extern super_remote_players_action_update g_stateless_super_remote_players_action_udpate;
extern wchar_t g_tracked_remote_player_position_updates[1024];
extern struct_game_allegiance_globals *game_allegiance_globals;
extern void (*game_data_input_function_list[0x2B])(widget_instance *widget);
extern game_engine_globals_t game_engine_globals;
extern game_engine_playlist_s game_engine_playlist;
extern struct game_engine *game_engines[8];
extern struct_game_globals * game_globals;
extern unsigned char game_initial_loading;
extern data_array *game_looping_sound_data;
extern game_sound_global_data *game_sound_globals;
extern struct game_state_globals game_state_globals;
extern game_statistics_globals_t game_statistics_globals;
extern game_time_globals_struct * game_time_globals;
extern struct game_time_statistics game_time_statistics;
extern game_variant game_variant_global;
extern object_type_definition garbage_data_definition;
extern int globalQuit;
extern const char *global_actor_mode_names[4];
extern float global_air_density;
extern float global_atmospheric_fog_density;
extern data_file_s global_bitmap_data_file;
extern bsp3d *global_bsp3d;
extern collision_bsp * global_collision_bsp;
extern __int16 global_communication_table_indices[57];
extern hs_global_external global_connection_dont_timeout_definition;
extern float global_convex_hull3d_delta;
extern float global_convex_hull3d_epsilon;
extern short global_current_render_target;
extern Direct3D *global_d3d;
extern _D3DCAPS9 global_d3d_caps;
extern D3DDevice * global_d3d_device;
extern _D3DPRESENT_PARAMETERS_ global_d3d_present_parameters;
extern const char *global_data_packet_groups_error_string; /* const: only ever holds string literals or 0 2026-07-31 (C4090) */
extern int *global_debug_key_down;
extern debug_key global_debug_key_list[12];
extern data_array * global_decal_data;
extern real_rgb_color global_default_animation_colors[4];
extern float global_default_animation_values[4];
extern _D3DDEVTYPE global_devicetype;
extern __int16 global_dialogue_event_count;
extern dialogue_event_status *global_dialogue_events;
extern __int16 global_difficulty_level;
extern const real_vector3d *global_down3d;
extern real_rgb_color global_effect_ambient;
extern _D3DXMACRO global_effect_macros[3];
extern const effect_marker_list *global_effect_marker_list;
extern ID3DXEffectPool *global_effect_pool;
extern unsigned char global_fog_enabled;
extern const real_vector2d *global_forward2d;
extern const real_vector3d *global_forward3d;
extern rasterizer_frame_begin_parameters global_frame_parameters;
extern unsigned char global_frame_rate_throttle;
extern game_globals_tag * global_game_globals;
extern netgame_goal global_goal[32];
extern float global_gravity;
extern const real_matrix4x3 *global_identity4x3;
extern const real_quaternion *global_identity_quaternion;
extern __int16 global_language_code;
extern const real_vector2d *global_left2d;
extern const real_vector3d *global_left3d;
extern bitmap_data *global_lightmap;
extern unsigned int global_local_random_seed;
extern const char *global_material_type_strings[];
extern int global_memory_index;
extern network_game_client *global_network_game_client;
extern network_game_server *global_network_game_server;
extern const real_rectangle2d *global_null_rectangle2d;
extern const real_rectangle3d *global_null_rectangle3d;
extern unsigned __int8 global_nvidia_broken_render_targets;
extern int global_object_marker;
extern int global_object_scenario_index;
extern const real_point3d *global_origin3d;
extern float global_physics_collision_depth;
extern unsigned int global_random_seed;
extern game_globals_rasterizer_data * global_rasterizer_data;
extern const real_argb_color *global_real_argb_black;
extern const real_argb_color *global_real_argb_blue;
extern const real_argb_color *global_real_argb_darkgreen;
extern const real_argb_color *global_real_argb_green;
extern const real_argb_color *global_real_argb_lightblue;
extern const real_argb_color *global_real_argb_orange;
extern const real_argb_color *global_real_argb_pink;
extern const real_argb_color *global_real_argb_purple;
extern const real_argb_color *global_real_argb_red;
extern const real_argb_color *global_real_argb_salmon;
extern const real_argb_color *global_real_argb_violet;
extern const real_argb_color *global_real_argb_white;
extern const real_argb_color *global_real_argb_yellow;
extern const real_rgb_color *global_real_rgb_black;
extern const real_rgb_color *global_real_rgb_blue;
extern const real_rgb_color *global_real_rgb_green;
extern const real_rgb_color *global_real_rgb_grey;
extern const real_rgb_color *global_real_rgb_red;
extern const real_rgb_color *global_real_rgb_white;
extern rasterizer_render_target global_render_targets[10];
extern __int16 global_reply_event_count;
extern dialogue_event_status *global_reply_events;
extern const real_vector3d *global_right3d;
extern saved_film global_saved_film;
extern scenario * global_scenario;
extern int global_scenario_index;
extern int global_screenshot_count;
extern short global_screenshot_size;
extern simple_decompressor_definition *global_self;
extern shader_effect global_shader_effect_additive;
extern shader_effect global_shader_effect_alpha_blended;
extern unsigned int global_shadow_color;
extern data_file_s global_sound_data_file;
extern play_stage global_stage;
extern structure_bsp * global_structure_bsp;
extern short global_structure_bsp_index;
extern cache_file_tag_instance * global_tag_instances;
extern real_argb_color global_temporary_render_color;
extern const firing_position *global_temporary_sort_firing_position_array;
extern __int16 global_temporary_sort_firing_position_count;
extern float global_ui_white_blue;
extern float global_ui_white_green;
extern float global_ui_white_red;
extern const real_vector3d *global_up3d;
extern game_variant global_variant;
extern unsigned int global_vector_palette[256];
extern float global_water_density;
extern float global_water_mass_over_radius_cubed;
extern rasterizer_window_begin_parameters global_window_parameters;
extern const real_point3d *global_z_axis3d;
extern const real_euler_angles2d *global_zero_angles2d;
extern const real_vector2d *global_zero_vector2d;
extern const real_vector3d *global_zero_vector3d;
extern breakable_surface_globals *globals;
extern glow_globals_type glow_globals;
extern float green;
extern float green_0;
extern float green_1;
extern __int16 group_index;
extern unsigned int hFlashDarken;
extern unsigned int hFlashInvert;
extern unsigned int hFlashLighten;
extern unsigned int hFlashMax;
extern unsigned int hFlashMin;
extern unsigned int hFlashTint;
extern unsigned int hModelEnvironmentNoMaskTechniques[12];
extern unsigned int hModelMultipurposeMaskTechniques[24];
extern unsigned int hVideoOffConvolveMaskThreeStage;
extern unsigned int hVideoOffConvolved;
extern unsigned int hVideoOffConvolvedFilterDesaturation;
extern unsigned int hVideoOffConvolvedFilterLight;
extern unsigned int hVideoOffConvolvedFilterLightAndDesaturation;
extern unsigned int hVideoOffConvolvedMask;
extern unsigned int hVideoOffConvolvedMaskFilterDesaturation;
extern unsigned int hVideoOffConvolvedMaskFilterLight;
extern unsigned int hVideoOffConvolvedMaskFilterLightAndDesaturation;
extern unsigned int hVideoOffNonConvolved;
extern unsigned int hVideoOn;
extern HALO_SOUND_SYSTEM *haloSoundSystem;
extern int halo_is_skip_private;
extern int halo_use_white_tex;
extern hardware_character_cache_struct hardware_character_cache;
extern int hcex_2x_rounds_per_shot;
extern int hcex_ai_drop_wpn_half_ammo;
extern float hcex_aim_assist_coeff;
extern int hcex_allow_covenant_weapon;
extern int hcex_allow_saved_film_recoring;
extern int hcex_always_shoot;
extern int hcex_arifle_ammo[2];
extern float hcex_arifle_compass[2];
extern void *hcex_bsp_vbuf;
extern int hcex_coop_local_player_index;
extern int hcex_coop_nticks_to_apply;
extern int hcex_coop_online_test_local;
extern int hcex_coop_update_number;
extern int hcex_cur_hs_thread;
extern int hcex_damage_indicators_ofsx;
extern int hcex_damage_indicators_ofsy;
extern float hcex_damage_indicators_scale;
extern int hcex_debug_effect_names;
extern int hcex_disable_motion_sensor;
extern int hcex_do_legacy_render;
extern int hcex_dont_skip_cine;
extern int hcex_double_damage_radius;
extern float hcex_fly_mode_speed_scale;
extern int hcex_force_one_tick;
extern int hcex_fp_model1[2];
extern int hcex_fp_model2[2];
extern real_matrix4x3 hcex_fp_model_matrices1[2][64];
extern real_matrix4x3 hcex_fp_model_matrices2[2][64];
extern char hcex_gamepad_buttons[4][16];
extern float hcex_hud_globals_scale;
extern int hcex_is_unlock_all_maps;
extern const char *hcex_last_fx;
extern int hcex_last_killed_in_body_part;
extern const char *hcex_last_vsh;
extern int hcex_load_checkpoint;
extern int hcex_malfunction_skull;
extern int hcex_material_effect_type;
extern int hcex_model_rend_disable;
extern void *hcex_models_ibuf;
extern void *hcex_models_vbuf;
extern int hcex_mythic_skull;
extern int hcex_off_aim_projectile;
extern int hcex_off_cine_screen_effect;
extern int hcex_off_halo_render;
extern int hcex_off_hud_element;
extern int hcex_off_tex_streaming;
extern int hcex_pjl_effect;
extern float hcex_plasma_pistol_heat[2];
extern float hcex_plasma_rifle_heat[2];
extern int hcex_recharge_on_melee;
extern int hcex_recharge_ticks[2];
extern float hcex_render_state_bitmap_scale;
extern int hcex_reset_single_on_die;
extern __int16 hcex_sThumbLX[4];
extern __int16 hcex_sThumbLY[4];
extern __int16 hcex_sThumbRX[4];
extern __int16 hcex_sThumbRY[4];
extern int hcex_screen_height;
extern int hcex_screen_width;
extern int hcex_spawning_player;
extern int hcex_switch_cam_mode;
extern int hcex_unit_drop_grenade_on_melee;
extern hs_compile_globals_t hs_compile_globals;
extern unsigned char hs_console_mode;
extern hs_global_external *hs_external_globals[482];
extern const hs_function_definition *hs_function_table[471];
extern data_array *hs_global_data;
extern unsigned char hs_model_animation_compression_enabled;
extern const char *hs_script_type_names[5];
extern data_array * hs_syntax_data;
extern unsigned char hs_syntax_data_allocated;
extern data_array * hs_thread_data;
extern void (*hs_token_enumerators[18])(void);
extern const char **hs_tokens_enumerate_results;    /* enumeration state: results array (dword_8445F6A4; was int-holding-pointer, x64 hazard) */
extern const char *hs_tokens_enumerate_substring;   /* enumeration state: search substring (dword_8445F698; was int-holding-pointer, x64 hazard) */
extern void (*hs_type_inspectors[49])(__int16 value_type, int value, char *buffer);
extern const char *hs_type_names[49];
extern const char *hs_type_string_default;
extern int hud_calculate_point_no_safearea_fit;
extern hs_global_external hud_filter_definition;
extern hud_globals_definition * hud_globals;
extern hud_messaging_globals_definition * hud_messaging_globals;
extern hud_messaging_parameters_definition *hud_msg_def;
extern hud_scripted_globals_definition *hud_scripted_globals;
extern const unsigned char icon_is_special[18];
extern const wchar_t *icon_names[40];
extern unsigned int ignore_game_input_time;
extern const char *ignore_maps[14];
extern transparent_geometry_group immediate_transparent_geometry_group;
extern unsigned __int8 in_error;
extern unsigned int index;
extern unsigned char initialized_0;
extern _input_abstraction_globals input_abstraction_globals;
extern input_globals_xbox input_globals;
extern const char *invalid_keys;
extern unsigned char is_scripted;
extern struct game_engine king_engine;
extern short king_engine_hills[64];
extern king_globals_type king_globals;
extern king_globals_type king_globals_baseline;
extern short last_attract_movie;
extern int last_decal_index_queried_by_lruv_cache;
extern unsigned int last_dpad_down[4];
extern unsigned int last_dpad_left[4];
extern unsigned int last_dpad_right[4];
extern unsigned int last_dpad_up[4];
extern int last_effect_index;
extern unsigned char last_iteration_field_map[64];
extern int last_left_analog_stick_x[4];
extern int last_left_analog_stick_y[4];
extern int last_player1_profile_index;
extern real_point3d last_positions[64];
extern unsigned char last_scripted;
extern int last_time;
extern leaf_map_globals_s leaf_map_globals;
extern unsigned char leaf_to_leaf_latency;
extern hs_global_external leaf_to_leaf_latency_definition;
extern unsigned int left_analog_stick_timer[4];
extern cluster_partition light_cluster_partition;
extern data_array * light_data;
extern object_type_definition light_fixture_data_definition;
extern render_lighting lighting_storage;
extern void *lights_game_globals;
extern lights_globals_t lights_globals;
extern unsigned int loading_screen_close_time_ms;
extern wchar_t loading_screen_connect_ip[32];
extern wchar_t loading_screen_map[64];
extern int loading_screen_natneg_cookie;
extern unsigned int loading_screen_open_time_ms;
extern int loading_screen_retry_count;
extern int loading_screen_state;
extern __int16 local_active_camouflage_debug_cache_count;
extern unsigned __int8 local_active_camouflage_debug_cached_flag;
extern unsigned __int8 local_active_camouflage_visibility_flag;
extern void *local_d3d_vertex_buffer;
extern void *local_d3d_vertex_buffer_0;
extern int local_d3d_vertex_buffer_ofs;
extern unsigned __int8 local_do_not_change_z_stencil_states;
extern unsigned __int8 local_environment_fog_screen_flag;
extern unsigned __int8 local_filthy_decal_fog_hack_enabled;
extern short local_framebuffer_blend_function;
extern transparent_geometry_group local_group;
extern int local_last_source_object_index;
extern short local_layer;
extern int local_lens_flare_count;
extern unsigned char local_lens_flare_occlusion_test_results[16128];
extern unsigned __int8 local_lens_flare_occlusion_test_results2[65544][2];
extern rasterizer_lens_flare_submit_parameters local_lens_flare_parameters[1024];
extern real_rgb_color local_lightmap_ambient_color;
extern unsigned __int8 local_lightmap_has_no_data;
extern unsigned __int8 local_lightmap_has_no_data_0;
extern float local_matrix_projection[5][4];
extern short local_model_effect_type;
extern const rasterizer_model_begin_parameters *local_parameters;
extern const rasterizer_model_begin_parameters *local_parameters_0;
extern unsigned __int8 local_parameters_queued_flag;
extern unsigned char local_pixel_shader_dirty_flag;
extern unsigned char local_planar_fog_flag;
extern __int16 local_player_index;
extern __int16 local_player_index_for_draw_string_and_hack_in_icons;
extern int local_player_log_level;
extern hs_global_external local_player_log_level_definition;
extern unsigned int local_player_update_rate;
extern hs_global_external local_player_update_rate_definition;
extern unsigned int local_player_vehicle_update_rate;
extern hs_global_external local_player_vehicle_update_rate_definition;
extern real_rgb_color local_shadow_color;
extern unsigned __int8 local_sky_flag;
extern lruv_cache *local_vertex_cache;
extern unsigned __int8 log_server_player_update_history;
extern hs_global_external log_server_player_update_history_definition;
extern data_array *looping_sound_data;
extern unsigned char loud_dialog_hack;
extern hs_global_external loud_dialog_hack_definition;
extern object_type_definition machine_data_definition;
extern int machine_to_player_table[32];
extern short magic_base_animation_seat_index;
extern short magic_number;
extern struct main_globals main_globals;
extern const unsigned int mapRGB4[4];
extern unsigned __int8 map_lost;
extern dynamic_array mapcycle_array;
extern char mask_technique_names[24][128];
extern float max_intensity;
extern float max_intensity_0;
extern float max_intensity_1;
extern char memory_unit_mapfile_name[256];
extern _field_type_definition message_delta_global_field_type_list[28];
extern struct metrics_globals metrics_globals;
extern const char *mode_str[2];
extern hs_global_external model_animation_bullshit0_definition;
extern hs_global_external model_animation_bullshit1_definition;
extern hs_global_external model_animation_bullshit2_definition;
extern hs_global_external model_animation_bullshit3_definition;
extern hs_global_external model_animation_compression_definition;
extern hs_global_external model_animation_data_compressed_size_definition;
extern hs_global_external model_animation_data_compression_savings_in_bytes_at_import_definition;
extern hs_global_external model_animation_data_compression_savings_in_bytes_definition;
extern hs_global_external model_animation_data_compression_savings_in_percent_definition;
extern hs_global_external model_animation_data_uncompressed_size_definition;
extern motion_sensor_globals_definition *motion_sensor_globals;
extern queued_mp_sound mp_sound_queue[5];
extern byte_swap_definition multi_vector_set_event_v1_bs_definition;
extern int multiplayer_map_list_count;
extern int multiplayer_map_list_size;
extern multiplayer_map_s *multiplayer_maps;
extern float music_gain_in_profile;
extern unsigned int mutex_count;
extern mutex mutex_pool[32];
extern hud_nav_point_player_datum *nav_point_data;
extern hs_global_external net_bandwidth_definition;
extern hs_global_external net_graph_enabled_definition;
extern hs_global_external net_graph_period_definition;
extern hs_global_external network_connect_timeout_definition;
extern unsigned __int8 new_campaign_begin_editing;
extern short new_campaign_controller_index;
extern const short next_field[3];
extern const short next_field_0[3];
extern int node_count;
extern cluster_partition noncollideable_object_cluster_partition;
extern int numeric_countdown_timer_milliseconds;
extern unsigned char numeric_countdown_timer_on;
extern void (*object_deleted_procs[3])(int);
extern struct object_globals * object_globals;
extern data_array * object_header_data;
extern float object_light_ambient_base;
extern hs_global_external object_light_ambient_base_definition;
extern float object_light_ambient_scale;
extern hs_global_external object_light_ambient_scale_definition;
extern unsigned char object_light_interpolate;
extern hs_global_external object_light_interpolate_definition;
extern float object_light_secondary_scale;
extern hs_global_external object_light_secondary_scale_definition;
extern data_array *object_list_data;
extern data_array *object_list_header_data;
extern memory_pool *object_memory_pool;
extern int *object_name_list;
extern unsigned char object_prediction;
extern hs_global_external object_prediction_definition;
extern object_type_definition *object_type_definitions[12];
extern observer_globals_t observer_globals;
extern __int16 observer_parameter_derivative_real_counts[5];
extern short observer_parameter_real_counts[5];
extern D3DQuery *occlusion_query[1024];
extern int oddball_baseline_rate;
extern hs_global_external oddball_baseline_rate_definition;
extern struct game_engine oddball_engine;
extern oddball_globals_type oddball_globals;
extern oddball_globals_type oddball_globals_baseline;
extern int offset_0;
extern const real_vector3d offsets[17];
extern float ofsx;
extern float ofsy;
extern unsigned int *old_ebp;
extern unsigned int oldtime;
extern unsigned __int8 once;
extern unsigned __int8 once_0;
extern unsigned __int8 once_1;
extern int optionNoNetwork;
extern int optionNoSound;
extern int optionNoVideo;
extern int optionSafe;
extern int overcharge_count;
extern achievements_info *p_achievements_info;
extern hs_global_external pad3_definition;
extern hs_global_external pad3_scale_definition;
extern __int16 parameter_types[2];
extern data_array *particle_data;
extern const char *particle_effect_marker_names[];
extern data_array *particle_systems;
extern pc_sound_cache_globals_t pc_sound_cache_globals;
extern pc_texture_cache_globals_struct pc_texture_cache_globals;
extern unsigned char *periodic_function_tables[12];
extern _persistant_game_data_info persistant_game_data_info;
extern persisted_camera_data persisted_cameras[2];
extern struct physical_memory_map_globals physical_memory_map_globals;
extern float pitch_scale;
extern object_type_definition placeholder_data_definition;
extern float planar_eye_density;
extern platform_sound_manager_definition *platform_definitions[2];
extern platform_sound_manager_definition platform_sound_dsound;
extern platoon_datum * platoon_array;
extern animation_playback *playback_codec[4];
extern int player1_last_used_profile_index;
extern char player1_profile_path[256];
extern hs_global_external player_autoaim_definition;
extern unsigned char player_autoaim_flag;
extern player_control_globals_t * player_control_globals;
extern data_array * player_data;
extern player_effect_globals_definition * player_effect_globals;
extern float player_look_pitch_rate[4];
extern float player_look_yaw_rate[4];
extern hs_global_external player_magnetism_definition;
extern unsigned char player_magnetism_flag;
extern _player_profile_globals player_profile_globals;
extern short player_spawn_count;
extern hs_global_external player_spawn_count_definition;
extern _player_ui_globals player_ui_globals;
extern players_global_data * players_globals;
extern _playlist_profile_globals playlist_profile_globals;
extern int pneed_clear;
extern int pneed_dump_unused;
extern int pneed_dump_used;
extern __int16 positive_table[256];
extern dynamic_array preview_list_array_bank[3];
extern int preview_list_current_bank;
extern unsigned char preview_list_has_default;
extern int previous_corrupt_player1_profile_index;
extern int previous_game_time;
extern float previous_projection_coefficients[4];
extern short previous_stencil_mode;
extern unsigned short processed_bsp_flags;
extern const unsigned int profile_color_table[18];
extern hs_global_external profile_display_definition;
extern hs_global_external profile_dump_frames_definition;
extern hs_global_external profile_dump_lost_frames_definition;
extern hs_global_external profile_graph_definition;
extern char *profile_log_path;
extern hs_global_external profile_timebase_ticks_definition;
extern object_type_definition projectile_data_definition;
extern int projectile_incremental_rate;
extern hs_global_external projectile_incremental_rate_definition;
extern data_array * prop_data;
extern int pshader_table_used[123];
extern data_array *pursuit_data;
extern unsigned char quickstart_network_game_active;
extern struct game_engine race_engine;
extern race_globals_type race_globals;
extern race_globals_type race_globals_baseline;
extern random_math_globals_s random_math_globals;
extern int random_seed_lock_count;
extern hs_global_external rasterizer_DXTC_noise_definition;
extern hs_global_external rasterizer_active_camouflage_definition;
extern hs_global_external rasterizer_active_camouflage_multipass_definition;
extern hs_global_external rasterizer_bump_mapping_definition;
extern hs_global_external rasterizer_d3dlight_attenuation0_definition;
extern hs_global_external rasterizer_d3dlight_attenuation1_definition;
extern hs_global_external rasterizer_d3dlight_attenuation2_definition;
extern hs_global_external rasterizer_d3dlight_falloff_definition;
extern hs_global_external rasterizer_d3dlight_phi_definition;
extern hs_global_external rasterizer_d3dlight_theta_definition;
extern hs_global_external rasterizer_debug_geometry_definition;
extern hs_global_external rasterizer_debug_geometry_multipass_definition;
extern hs_global_external rasterizer_debug_meter_shader_definition;
extern hs_global_external rasterizer_debug_model_lod_definition;
extern hs_global_external rasterizer_debug_model_vertices_definition;
extern rasterizer_debug_options_struct rasterizer_debug_options;
extern hs_global_external rasterizer_debug_transparents_definition;
extern hs_global_external rasterizer_detail_objects_definition;
extern hs_global_external rasterizer_detail_objects_offset_multiplier_definition;
extern hs_global_external rasterizer_draw_first_person_weapon_first_definition;
extern hs_global_external rasterizer_dynamic_lit_geometry_definition;
extern hs_global_external rasterizer_dynamic_screen_geometry_definition;
extern hs_global_external rasterizer_dynamic_unlit_geometry_definition;
extern hs_global_external rasterizer_effects_level_definition;
extern hs_global_external rasterizer_environment_alpha_testing_definition;
extern hs_global_external rasterizer_environment_decals_definition;
extern hs_global_external rasterizer_environment_definition;
extern void (*rasterizer_environment_diffuse_light_draw_function)(const shader *, __int16, int, int, int, const vertex_buffer *);
extern hs_global_external rasterizer_environment_diffuse_lights_definition;
extern void (*rasterizer_environment_diffuse_texture_draw_function)(const shader *, __int16, int, int, int, const vertex_buffer *);
extern hs_global_external rasterizer_environment_diffuse_textures_definition;
extern hs_global_external rasterizer_environment_fog_definition;
extern int rasterizer_environment_fog_off;
extern hs_global_external rasterizer_environment_fog_screen_definition;
extern hs_global_external rasterizer_environment_lightmaps_definition;
extern void (*rasterizer_environment_lightmaps_draw_function)(const shader *, __int16, int, int, int, const vertex_buffer *);
extern hs_global_external rasterizer_environment_reflection_lightmap_mask_definition;
extern hs_global_external rasterizer_environment_reflection_mirrors_definition;
extern hs_global_external rasterizer_environment_reflections_definition;
extern hs_global_external rasterizer_environment_shadows_definition;
extern hs_global_external rasterizer_environment_specular_lightmaps_definition;
extern hs_global_external rasterizer_environment_specular_lights_definition;
extern hs_global_external rasterizer_environment_specular_mask_definition;
extern hs_global_external rasterizer_environment_transparents_definition;
extern hs_global_external rasterizer_far_clip_distance_definition;
extern hs_global_external rasterizer_filthy_decal_fog_hack_definition;
extern hs_global_external rasterizer_first_person_weapon_far_clip_distance_definition;
extern hs_global_external rasterizer_first_person_weapon_near_clip_distance_definition;
extern hs_global_external rasterizer_floating_point_zbuffer_definition;
extern hs_global_external rasterizer_fog_atmosphere_definition;
extern hs_global_external rasterizer_fog_plane_definition;
extern __int64 rasterizer_fps_accumulation_frame_index;
extern __int64 rasterizer_fps_accumulation_time;
extern hs_global_external rasterizer_fps_definition;
extern hs_global_external rasterizer_frame_bounds_bottom_definition;
extern hs_global_external rasterizer_frame_bounds_left_definition;
extern hs_global_external rasterizer_frame_bounds_right_definition;
extern hs_global_external rasterizer_frame_bounds_top_definition;
extern rasterizer_frame_statistics_s rasterizer_frame_statistics;
extern hs_global_external rasterizer_framerate_stabilization_definition;
extern hs_global_external rasterizer_framerate_throttle_definition;
extern void (*rasterizer_glass_draw_diffuse)(const transparent_geometry_group *);
extern void (*rasterizer_glass_draw_reflection)(const transparent_geometry_group *, __int16);
extern void (*rasterizer_glass_draw_tint)(const transparent_geometry_group *);
extern rasterizer_globals_struct rasterizer_globals;
extern hs_global_external rasterizer_hud_motion_sensor_definition;
extern int rasterizer_initialized;
extern hs_global_external rasterizer_lens_flares_definition;
extern hs_global_external rasterizer_lens_flares_occlusion_debug_definition;
extern hs_global_external rasterizer_lens_flares_occlusion_definition;
extern hs_global_external rasterizer_lightmap_ambient_definition;
extern hs_global_external rasterizer_lightmap_mode_definition;
extern hs_global_external rasterizer_lightmaps_filtering_definition;
extern hs_global_external rasterizer_lightmaps_incident_radiosity_definition;
extern rasterizer_lights_struct rasterizer_lights;
extern hs_global_external rasterizer_mode_definition;
extern unsigned __int8 rasterizer_model_cortana_hack;
extern void (*rasterizer_model_draw_environment_shader)(const shader *, __int16, const triangle_buffer *, int, int, const vertex_buffer *, int);
extern void (*rasterizer_model_draw_model_shader)(const shader *, __int16, const triangle_buffer *, int, int, const vertex_buffer *, int);
extern hs_global_external rasterizer_model_lighting_ambient_definition;
extern hs_global_external rasterizer_model_transparents_definition;
extern hs_global_external rasterizer_models_definition;
extern unsigned __int8 rasterizer_motion_sensor_begin_said_to_draw;
extern hs_global_external rasterizer_near_clip_distance_definition;
extern hs_global_external rasterizer_plasma_energy_definition;
extern hs_global_external rasterizer_profile_log_definition;
extern hs_global_external rasterizer_profile_objectlock_time_definition;
extern hs_global_external rasterizer_profile_print_locks_definition;
extern hs_global_external rasterizer_ray_of_buddha_definition;
extern hs_global_external rasterizer_refresh_rate_definition;
extern hs_global_external rasterizer_safe_frame_bounds_definition;
extern hs_global_external rasterizer_screen_effects_definition;
extern hs_global_external rasterizer_screen_flashes_definition;
extern hs_global_external rasterizer_secondary_render_target_debug_definition;
extern hs_global_external rasterizer_shadows_convolution_definition;
extern hs_global_external rasterizer_shadows_debug_definition;
extern hs_global_external rasterizer_smart_definition;
extern hs_global_external rasterizer_soft_filter_definition;
extern hs_global_external rasterizer_splitscreen_VB_optimization_definition;
extern hs_global_external rasterizer_stats_definition;
extern hs_global_external rasterizer_stencil_mask_definition;
extern hs_global_external rasterizer_transparent_pixel_counter_definition;
extern hs_global_external rasterizer_water_definition;
extern void (*rasterizer_water_draw)(const transparent_geometry_group *);
extern hs_global_external rasterizer_water_mipmapping_definition;
extern hs_global_external rasterizer_wireframe_definition;
extern hs_global_external rasterizer_zbias_definition;
extern hs_global_external rasterizer_zoffset_definition;
extern hs_global_external rasterizer_zsprites_definition;
extern unsigned char recompile;
extern void (*reconnect_to_structure_bsp_procs[13])(void);
extern unsigned char recover_saved_games_hack;
extern hs_global_external recover_saved_games_hack_definition;
extern unsigned __int8 recursion_lock;
extern float red;
extern float red_0;
extern float red_1;
extern int remote_player_action_baseline_update_rate;
extern hs_global_external remote_player_action_baseline_update_rate_definition;
extern int remote_player_action_update_rate;
extern hs_global_external remote_player_action_update_rate_definition;
extern int remote_player_log_level;
extern hs_global_external remote_player_log_level_definition;
extern int remote_player_position_baseline_update_rate;
extern hs_global_external remote_player_position_baseline_update_rate_definition;
extern int remote_player_position_update_rate;
extern hs_global_external remote_player_position_update_rate_definition;
extern int remote_player_vehicle_baseline_update_rate;
extern hs_global_external remote_player_vehicle_baseline_update_rate_definition;
extern int remote_player_vehicle_update_rate;
extern hs_global_external remote_player_vehicle_update_rate_definition;
extern render_globals render;
extern unsigned char render_camera_debug_this_fucking_frustum;
extern hs_global_external render_contrails_definition;
extern int render_graph;
extern int render_infos;
extern hs_global_external render_model_index_counts_definition;
extern hs_global_external render_model_markers_definition;
extern hs_global_external render_model_no_geometry_definition;
extern hs_global_external render_model_nodes_definition;
extern hs_global_external render_model_vertex_counts_definition;
extern render_object_globals_struct render_object_globals;
extern unsigned char render_particle_systems_enabled;
extern hs_global_external render_particles_definition;
extern unsigned char render_particles_enabled;
extern hs_global_external render_psystems_definition;
extern short render_screen_flash_type_map[7];
extern unsigned char render_shadows;
extern hs_global_external render_shadows_definition;
extern render_sky_globals_t render_sky_globals;
extern hs_global_external render_wsystems_definition;
extern ui_widget_replace_function replace_function_list[4];
extern unsigned char reset_all;
extern char result_0[260];
extern unsigned __int16 result_1[2];
extern unsigned __int16 result_2[32];
extern unsigned __int16 result_3[32];
extern char rider_ejection;
extern hs_global_external rider_ejection_definition;
extern hs_global_external run_game_scripts_definition;
extern float sPROJECTILE_CLIENT_TO_SERVER_POSITION_TOLERANCE;
extern float sPROJECTILE_CLIENT_TO_SERVER_POSITION_TOLERANCE_0;
extern float sPROJECTILE_CLIENT_TO_SERVER_POSITION_TOLERANCE_1;
extern _LARGE_INTEGER s_ClockFrequency;
extern char *s_file_name;
extern int s_local_update_id;
extern int s_vehicle_waiting_time;
extern int s_waiting_time;
extern unsigned char saved_film_buffer[16384];
extern int saved_film_buffer_head;
extern int saved_film_buffer_tail;
extern data_packet_group_definition saved_film_group;
extern data_packet_group_packet saved_film_group_packets[4];
extern _saved_game_files_globals saved_game_files_globals;
extern float scale_2;
extern float scale_crosshair;
extern float scales[3];
extern scenario_global_data *scenario_globals;
extern const char *scenario_paths[10];
extern char *scenario_paths_0[10];
extern object_type_definition scenery_data_definition;
extern char scratch_disk_root[261];
extern int screen_flash_type;
extern int screen_flash_type_0;
extern int screen_flash_type_1;
extern hs_global_external screenshot_count_definition;
extern hs_global_external screenshot_size_definition;
extern vector_avoidance_ray sense_rays[9];
extern int sequential_counter;
extern void *shader_bin_handle;
extern rasterizer_dx9_shader shader_table[123];
extern unsigned char shadow_restored;
extern unsigned __int8 shadow_setup;
extern unsigned __int8 shadow_used;
extern unsigned char should_force_hot_update;
extern unsigned char should_play_multiplayer_hit_sound;
extern hs_global_external should_play_multiplayer_hit_sound_definition;
extern float side_scale;
extern _single_player_level_data single_player_level_data[10];
extern float sizes[3];
extern struct game_engine slayer_engine;
extern slayer_globals_type slayer_globals;
extern slayer_globals_type slayer_globals_baseline;
extern hs_global_external slow_server_startup_safety_zone_in_seconds_definition;
extern unsigned int sound_cache_page_count;
extern short sound_cache_size;
extern short sound_channel_type_flags[4];
extern sound_channel_datum sound_channels[256];
extern sound_class_datum *sound_class_data;
extern const char *sound_class_names[51];
extern sound_class_definition sound_classes[51];
extern data_array * sound_data;
extern float sound_fade_exponent;
extern float sound_gain_under_dialog;
extern hs_global_external sound_gain_under_dialog_definition;
extern unsigned char sound_is_queueable[48];
extern sound_manager_globals_t sound_manager_globals;
extern object_type_definition sound_scenery_data_definition;
extern float specular_light_brightness;
extern short specular_light_vertex_shader_permutation_index;
extern float speed;
extern unsigned char speed_hack_detection;
extern hs_global_external speed_hack_detection_definition;
extern int speed_hack_log_level;
extern hs_global_external speed_hack_log_level_definition;
extern float speed_scale;
extern float split_sensor_ofsx;
extern float split_sensor_ofsy;
extern squad_datum * squad_array;
extern _stack_walk_globals stack_walk_globals;
extern const char *str_1[2];
extern wchar_t string_data[1024];
extern structure_decals_globals_definition *structure_decals_globals;
extern structure_render_globals_data structure_render_globals;
extern float structure_sphere_threshold;
extern struct structure_visibility_globals structure_visibility_globals;
extern unsigned char structures_use_pvs_for_vs;
extern hs_global_external structures_use_pvs_for_vs_definition;
extern struct game_engine stub_engine;
extern unsigned char stun_enable;
extern hs_global_external stun_enable_definition;
extern unsigned char supports_occlusion_test;
extern hs_global_external sv_mapcycle_timeout_definition;
extern int sv_max_players_value;
extern hs_global_external sv_maxplayers_definition;
extern wchar_t sv_name_value[16];
extern wchar_t sv_password_value[9];
extern hs_global_external sv_public_definition;
extern unsigned char sv_public_value;
extern data_array * swarm_component_data;
extern data_array * swarm_data;
extern float sweep_theta;
extern char symbol_buffer[0x4000];
extern data_array *system_particles;
extern data_array *team_data;
extern hs_global_external temporary_hud_definition;
extern terminal_globals_t terminal_globals;
extern unsigned char terminal_render_enable;
extern float test_0;
extern text_bounds_globals_t text_bounds_globals;
extern _text_pick_globals text_pick_globals;
extern hs_global_external texture_cache_graph_definition;
extern hs_global_external texture_cache_list_definition;
extern float theta;
extern thread thread_pool[32];
extern byte_swap_definition throttle_event_data_bs_definition;
extern byte_swap_definition throttle_set_event_v1_bs_definition;
extern int timeDemo;
extern unsigned int time_of_first_device_insertion;
extern unsigned int time_of_last_tab;
extern unsigned int time_samples[60];
extern int timeout_for_endgame_sound;
extern unsigned char *transition_function_tables[6];
extern void (*translate_funcs[2][2])(flying_camera *camera);
extern __int16 transparent_geometry_attached_group_count;
extern int transparent_geometry_group_count;
extern int transparent_geometry_group_count2;
extern short *transparent_geometry_group_sorted_indices;
extern transparent_geometry_group *transparent_geometry_groups;
extern transparent_geometry_group *transparent_geometry_groups2;
extern unsigned char transport_dumping;
extern hs_global_external transport_dumping_definition;
extern unsigned char trouble_brewed_this_frame;
extern unsigned __int8 trouble_brewing_dialog_visible;
extern int trouble_is_brewing_bitmap_tag;
extern unsigned int trouble_is_brewing_time;
extern int (*typecasting_procedures[49][49])(int);
extern real_argb_color ui_plasma_effect_color;
extern unit_control_data_entry *unit_control_data_map[4];
extern unit_control_data_entry unit_control_v1_map[10];
extern unit_control_data_entry unit_control_v2_map[10];
extern unit_control_data_entry unit_control_v3_map[10];
extern unit_control_data_entry unit_control_v4_map[10];
extern int unit_focus;
extern struct unit_globals *unit_globals;
extern unit_hud_globals_definition *unit_hud_globals;
extern real_vector3d unit_offset;
extern _update_client_globals update_client_globals;
extern void (*update_funcs[2])(flying_camera *, const camera_control *, observer_command *);
extern _update_server_globals update_server_globals;
extern unsigned char use_fullscreen;
extern unsigned char use_new_vehicle_update_scheme;
extern hs_global_external use_new_vehicle_update_scheme_definition;
extern unsigned __int8 use_roll;
extern unsigned char use_super_remote_players_action_update;
extern hs_global_external use_super_remote_players_action_update_definition;
extern animation_playback v1_playback;
extern director_variable_definition variables[4];
extern byte_swap_definition vector_char_difference_data_bs_definition;
extern byte_swap_definition vector_short_difference_data_bs_definition;
extern object_type_definition vehicle_data_definition;
extern int vehicle_incremental_rate;
extern hs_global_external vehicle_incremental_rate_definition;
extern vehicle_remapper_s vehicle_remapper;
extern dynamic_screen_vertex vertex_data[4];
extern dynamic_unlit_vertex vertex_data_0[4];
extern dynamic_screen_vertex vertex_data_1[4];
extern dynamic_screen_vertex vertex_data_2[4];
extern dynamic_unlit_vertex vertex_data_3[4];
extern vibrate_globals_s *vibrate_globals;
extern int video_gamma_setting;
extern int video_resolution_count;
extern video_resolution_s video_resolutions[32];
extern unsigned __int8 video_settings_saved;
extern unsigned __int8 video_test_save_confirmed;
extern virtual_keyboard_globals_t virtual_keyboard_globals;
extern int vneed_clear;
extern int vneed_dump_unused;
extern int vneed_dump_used;
extern vertex_shader_declaration vsd_table[18];
extern vertex_shader_function vsf_table[65];
extern float vsh_constants__nodematrices[528];
extern float vsh_constants__pointlight[20];
extern int vshader_table_used[65];
extern unsigned int walk_up_current_frame;
extern unsigned char want_to_teardown_networking;
extern unsigned __int8 warned;
extern int warned_2;
extern int warned_3;
extern unsigned char warned_4;
extern unsigned char warned_5;
extern unsigned char warned_6;
extern unsigned char warned_7;
extern unsigned char warned_8;
extern unsigned __int8 warned_9;
extern unsigned __int8 water_needs_update_flag;
extern unsigned char water_visible_for_window_flag;
extern unsigned char we_are_at_the_main_menu;
extern object_type_definition weapon_data_definition;
extern int weapon_effect_owner;
extern weapon_hud_globals_definition *weapon_hud_globals;
extern int weapon_incremental_rate;
extern hs_global_external weapon_incremental_rate_definition;
extern byte_swap_definition weapon_index_event_data_bs_definition;
extern byte_swap_definition weapon_index_set_event_v1_bs_definition;
extern unsigned char weather;
extern hs_global_external weather_definition;
extern data_array *weather_particle_data;
extern weather_particle_system_globals_data weather_particle_system_globals;
extern widget_batch widget_batches[5];
extern data_array *widget_data;
extern rasterizer_dx9_shader *widget_dxeffect_shader;
extern _widget_globals widget_globals;
extern unsigned char widget_instance_going_back_to_previous;
extern stack_memory_pool *widget_memory_pool;
extern unsigned int widget_specular_color;
extern widget_state widget_state_current;
extern widget_state widget_state_new;
extern int widget_time_stamp;
extern widget_type_definition widget_type_definitions[5];
extern struct render_window window;
extern struct render_window window_0[3];
extern float wtPrimary[3];
extern float yaw_scale;

/* Globals whose canonical TYPED declaration lives in a dedicated header
 * (the src/data storage is a size-equal byte-blob alias). Include that header
 * for the typed view; NOT redeclared here to avoid a conflicting decl. */
/* cache_file_globals -> "cache_file_runtime_globals.h" */
/* dynamic_triangles -> "dynamic_triangles.h" */
/* hs_runtime_globals -> "hs_runtime_globals.h" */
/* light_volume_globals -> "light_volume_globals.h" */
/* lightning_globals -> "lightning_globals.h" */
/* structure_globals -> "structure_globals.h" */
/* wind_globals -> "wind_globals.h" */
/* xbox_game_state_globals -> "xbox_game_state_globals.h" */

#endif /* BLAM_DATA_GLOBALS_H */
