#ifndef ERROR_TYPE_H
#define ERROR_TYPE_H

/* UI/deferred error codes passed to display_error_deferred / display_error.
 * DB anonymous enum _7A693951F911B4BD6361056513F28766 (value_name spellings verbatim). */
typedef enum error_type
{
    _error_unknown = 0,
    _error_network_generic = 1,
    _error_network_join_game_closed = 2,
    _error_network_join_game_generic = 3,
    _error_network_server_shut_down = 4,
    _error_network_connected_play_no_network = 5,
    _error_network_connection_lost = 6,
    _error_network_failed_to_join_game = 7,
    _error_network_out_of_sync_alert = 8,
    _error_network_trouble_is_brewing = 9,
    _error_network_unused10 = 10,
    _error_controller_generic = 11,
    _error_controller_unplugged_start_to_continue = 12,
    _error_controller_unplugged = 13,
    _error_controller_memory_card = 14,
    _error_controller_saving_file_warning = 15,
    _error_controller_creating_player_profile_warning = 16,
    _error_controller_creating_game_settings_file_warning = 17,
    _error_controller_coop_controller_conflict = 18,
    _error_controller_coop_requires_two_controllers = 19,
    _error_controller_unused10 = 20,
    _error_insert_quarter = 21,
    _error_warning_revert_to_saved_progress_will_be_lost = 22,
    _error_warning_restart_level_progress_will_be_lost = 23,
    _error_warning_delete_player_profile = 24,
    _error_warning_delete_multiplayer_profile = 25,
    _error_cannot_delete_default_game_settings = 26,
    _error_already_a_saved_game_file_with_that_name = 27,
    _error_warning_are_you_sure_you_want_to_discard_changes = 28,
    _error_cannot_create_saved_game_file_with_empty_name = 29,
    _error_warning_saving_checkpoint = 30,
    _error_warning_saved_game_file_damaged = 31,
    _error_warning_unused10 = 32,
    _error_hard_drive_not_enough_free_space = 33,
    _error_hard_drive_maximum_saved_game_files = 34,
    _error_media_damaged = 35,
    _error_maximum_game_files_created = 36,
    _error_unable_to_create_player_profile = 37,
    _error_unable_to_create_multiplayer_game_file = 38,
    _error_saved_game_state_corrupt = 39,
    _error_gamespy_sb = 40,
    _error_video_changed = 41,
    _error_gamespy_password = 42,
    _error_unable_to_join_server = 43,
    _error_invalid_connect_request = 44,
    _error_incorrect_password = 45,
    _error_game_is_full = 46,
    _error_invalid_cd_key = 47,
    _error_cd_key_inuse = 48,
    _error_banned_from_server = 49,
    _error_kicked_from_server = 50,
    _error_pre_testing_video = 51,
    _error_checkpoint_saved = 52,
    _error_invalid_address = 53,
    _error_no_profile_selected = 54,
    _error_unknown_protocol_version = 55,
    _error_server_newer = 56,
    _error_client_newer = 57,
    _error_need_admin_privileges = 58,
    _error_deleting_savegame = 59,
    NUMBER_OF_ERROR_CODES = 60
} error_type;

#endif /* ERROR_TYPE_H */
