#ifndef NT_EXCEPTION_CODES_H
#define NT_EXCEPTION_CODES_H

/* nt_exception_codes — the standard Windows NT structured-exception codes consumed by
 * exception_code_get_string. Values are the canonical STATUS_* NTSTATUS constants from winnt.h
 * (EXCEPTION_* are the winbase.h aliases for the same values). Each define is guarded so this
 * header coexists with <windows.h> if a TU pulls both in. */

#ifndef EXCEPTION_DATATYPE_MISALIGNMENT
#define EXCEPTION_DATATYPE_MISALIGNMENT     0x80000002u /* STATUS_DATATYPE_MISALIGNMENT */
#endif
#ifndef EXCEPTION_BREAKPOINT
#define EXCEPTION_BREAKPOINT                0x80000003u /* STATUS_BREAKPOINT */
#endif
#ifndef EXCEPTION_SINGLE_STEP
#define EXCEPTION_SINGLE_STEP               0x80000004u /* STATUS_SINGLE_STEP */
#endif
#ifndef EXCEPTION_ACCESS_VIOLATION
#define EXCEPTION_ACCESS_VIOLATION          0xC0000005u /* STATUS_ACCESS_VIOLATION */
#endif
#ifndef EXCEPTION_NONCONTINUABLE_EXCEPTION
#define EXCEPTION_NONCONTINUABLE_EXCEPTION  0xC0000025u /* STATUS_NONCONTINUABLE_EXCEPTION */
#endif
#ifndef EXCEPTION_ARRAY_BOUNDS_EXCEEDED
#define EXCEPTION_ARRAY_BOUNDS_EXCEEDED     0xC000008Cu /* STATUS_ARRAY_BOUNDS_EXCEEDED */
#endif
#ifndef EXCEPTION_FLT_DENORMAL_OPERAND
#define EXCEPTION_FLT_DENORMAL_OPERAND      0xC000008Du /* STATUS_FLOAT_DENORMAL_OPERAND */
#endif
#ifndef EXCEPTION_FLT_DIVIDE_BY_ZERO
#define EXCEPTION_FLT_DIVIDE_BY_ZERO        0xC000008Eu /* STATUS_FLOAT_DIVIDE_BY_ZERO */
#endif
#ifndef EXCEPTION_FLT_INEXACT_RESULT
#define EXCEPTION_FLT_INEXACT_RESULT        0xC000008Fu /* STATUS_FLOAT_INEXACT_RESULT */
#endif
#ifndef EXCEPTION_FLT_INVALID_OPERATION
#define EXCEPTION_FLT_INVALID_OPERATION     0xC0000090u /* STATUS_FLOAT_INVALID_OPERATION */
#endif
#ifndef EXCEPTION_FLT_OVERFLOW
#define EXCEPTION_FLT_OVERFLOW              0xC0000091u /* STATUS_FLOAT_OVERFLOW */
#endif
#ifndef EXCEPTION_FLT_STACK_CHECK
#define EXCEPTION_FLT_STACK_CHECK           0xC0000092u /* STATUS_FLOAT_STACK_CHECK */
#endif
#ifndef EXCEPTION_FLT_UNDERFLOW
#define EXCEPTION_FLT_UNDERFLOW             0xC0000093u /* STATUS_FLOAT_UNDERFLOW */
#endif
#ifndef EXCEPTION_INT_DIVIDE_BY_ZERO
#define EXCEPTION_INT_DIVIDE_BY_ZERO        0xC0000094u /* STATUS_INTEGER_DIVIDE_BY_ZERO */
#endif
#ifndef EXCEPTION_INT_OVERFLOW
#define EXCEPTION_INT_OVERFLOW              0xC0000095u /* STATUS_INTEGER_OVERFLOW */
#endif
#ifndef EXCEPTION_PRIV_INSTRUCTION
#define EXCEPTION_PRIV_INSTRUCTION          0xC0000096u /* STATUS_PRIVILEGED_INSTRUCTION */
#endif

#endif /* NT_EXCEPTION_CODES_H */

// nt_exception_codes: standard winnt.h/winbase.h NTSTATUS exception constants (documented values; not a DB enum)
