#ifndef RASTERIZER_VERTEX_SHADER_INDEX_H
#define RASTERIZER_VERTEX_SHADER_INDEX_H

/* Vertex-shader slot indices passed to rasterizer_dx9_shaders_vshader9_get().
 * DB anonymous enum _48C73337F1F6FA5002623CD6EBB0FE21 (verbatim). */
enum rasterizer_vertex_shader_index
{
    _vs_convolution = 0,
    _vs_debug = 1,
    _vs_decal = 2,
    _vs_detail_object_type0 = 3,
    _vs_detail_object_type1 = 4,
    _vs_effect = 5,
    _vs_effect_multitexture = 6,
    _vs_effect_multitexture_screenspace = 7,
    _vs_effect_zsprite = 8,
    _vs_environment_diffuse_light = 9,
    _vs_environment_diffuse_light_ff = 10,
    _vs_environment_fog = 11,
    _vs_environment_fog_screen = 12,
    _vs_environment_lightmap = 13,
    _vs_environment_reflection_bumped = 14,
    _vs_environment_reflection_flat = 15,
    _vs_environment_reflection_lightmap_mask = 16,
    _vs_environment_reflection_mirror = 17,
    _vs_environment_reflection_radiosity = 18,
    _vs_environment_shadow = 19,
    _vs_environment_specular_light = 20,
    _vs_environment_specular_spot_light = 21,
    _vs_environment_specular_lightmap = 22,
    _vs_environment_texture = 23,
    _vs_lens_flare = 24,
    _vs_model_fogged = 25,
    _vs_model = 26,
    _vs_model_skin_ff = 27,
    _vs_model_fast = 28,
    _vs_model_scenery = 29,
    _vs_model_active_camouflage = 30,
    _vs_model_active_camouflage_ff = 31,
    _vs_model_fog_screen = 32,
    _vs_model_shadow = 33,
    _vs_model_zbuffer = 34,
    _vs_screen = 35,
    _vs_screen2 = 36,
    _vs_transparent_generic = 37,
    _vs_transparent_generic_lit_m = 38,
    _vs_transparent_generic_m = 39,
    _vs_transparent_generic_object_centered = 40,
    _vs_transparent_generic_object_centered_m = 41,
    _vs_transparent_generic_reflection = 42,
    _vs_transparent_generic_reflection_m = 43,
    _vs_transparent_generic_screenspace = 44,
    _vs_transparent_generic_screenspace_m = 45,
    _vs_transparent_generic_viewer_centered = 46,
    _vs_transparent_generic_viewer_centered_m = 47,
    _vs_transparent_glass_diffuse_light = 48,
    _vs_transparent_glass_diffuse_light_m = 49,
    _vs_transparent_glass_reflection_bumped = 50,
    _vs_transparent_glass_reflection_bumped_m = 51,
    _vs_transparent_glass_reflection_flat = 52,
    _vs_transparent_glass_reflection_flat_m = 53,
    _vs_transparent_glass_reflection_mirror = 54,
    _vs_transparent_glass_tint = 55,
    _vs_transparent_glass_tint_m = 56,
    _vs_transparent_meter = 57,
    _vs_transparent_meter_m = 58,
    _vs_transparent_plasma_m = 59,
    _vs_transparent_water_opacity = 60,
    _vs_transparent_water_opacity_m = 61,
    _vs_transparent_water_reflection = 62,
    _vs_transparent_water_reflection_m = 63,
    _vs_widget = 64,
    NUMBER_OF_VERTEX_SHADERS = 65
};

#endif /* RASTERIZER_VERTEX_SHADER_INDEX_H */
