#ifndef RENDER_LIMITS_H
#define RENDER_LIMITS_H

/* render_limits — fixed capacities of the render globals (rendered clusters/lights/surfaces
 * arrays). DB-verified via types_enum_values $C9DEBE5901A29F209606714D7CDC25C3. */
enum render_limits {
	MAXIMUM_RENDERED_DISTANT_LIGHTS = 2,
	MAXIMUM_RENDERED_POINT_LIGHTS = 2,
	MAXIMUM_LENS_FLARES_PER_LIGHT = 8,
	MAXIMUM_QUEUED_LENS_FLARES = 8,
	MAXIMUM_RENDERED_CLUSTERS = 128,
	MAXIMUM_RENDERED_LIGHTS = 128,
	MAXIMUM_LIGHTS_PER_MAP = 896,
	MAXIMUM_RENDERED_ENVIRONMENT_SURFACES = 16384,
	MAXIMUM_SURFACES_PER_STRUCTURE = 131072,
};

#endif /* RENDER_LIMITS_H */
