#ifndef SCENARIO_CONSTANTS_H
#define SCENARIO_CONSTANTS_H

/* Scenario tag block capacity constants. */
enum scenario_constants {
	MAXIMUM_SKIES_PER_SCENARIO = 8,
	MAXIMUM_STRUCTURE_BSPS_PER_SCENARIO = 16,
	MAXIMUM_CHILD_SCENARIOS_PER_SCENARIO = 16,
	MAXIMUM_FUNCTIONS_PER_SCENARIO = 32,
	MAXIMUM_CUTSCENE_TITLES_PER_SCENARIO = 64,
	MAXIMUM_VEHICLE_DATUMS_PER_SCENARIO = 80,
	MAXIMUM_SCENARIO_OBJECT_PALETTE_ENTRIES_PER_BLOCK = 100,
	MAXIMUM_CONTROL_DATUMS_PER_SCENARIO = 100,
	MAXIMUM_DEVICE_GROUPS_PER_SCENARIO = 128,
	MAXIMUM_DECAL_PALETTES_PER_SCENARIO = 128,
	MAXIMUM_WEAPON_DATUMS_PER_SCENARIO = 128,
	MAXIMUM_BIPED_DATUMS_PER_SCENARIO = 128,
	MAXIMUM_SCENARIO_NETGAME_FLAGS_PER_SCENARIO = 200,
	MAXIMUM_SCENARIO_NETGAME_EQUIPMENT_PER_SCENARIO = 200,
	MAXIMUM_SCENARIO_STARTING_EQUIPMDNG_PER_SCENARIO = 200,   /* name verbatim from DB (sic) */
	MAXIMUM_SCENARIO_PLAYERS_PER_BLOCK = 256,
	MAXIMUM_TRIGGER_VOLUMES_PER_SCENARIO = 256,
	MAXIMUM_SOUND_SCENERY_DATUMS_PER_SCENARIO = 256,
	MAXIMUM_EQUIPMENT_DATUMS_PER_SCENARIO = 256,
	MAXIMUM_MACHINE_DATUMS_PER_SCENARIO = 400,
	MAXIMUM_LIGHT_FIXTURE_DATUMS_PER_SCENARIO = 500,
	MAXIMUM_OBJECT_NAMES_PER_SCENARIO = 512,
	MAXIMUM_CUTSCENE_FLAGS_PER_SCENARIO = 512,
	MAXIMUM_CUTSCENE_CAMERA_POINTS_PER_SCENARIO = 512,
	MAXIMUM_EDITOR_COMMENTS = 1024,
	MAXIMUM_SCENERY_DATUMS_PER_SCENARIO = 2000,
	MAXIMUM_EDITOR_COMMENT_LENGTH = 16384,
	MAXIMUM_DECALS_PER_SCENARIO = 65536,
	MAXIMUM_EDITOR_SCENARIO_DATA_SIZE = 65536,
};

#endif /* SCENARIO_CONSTANTS_H */

// scenario_constants: DB-verified via types_enum_values $A7E13B46EF406C344EB9EA066F2A7500
