#pragma once
/* hkpShapeType — Havok physics shape-type ids (DB types_enum_values hkpShapeType, 36 values). */
enum hkpShapeType
{
    HK_SHAPE_INVALID                = 0,
    HK_SHAPE_SPHERE                 = 1,
    HK_FIRST_SHAPE_TYPE             = 1,
    HK_SHAPE_CYLINDER               = 2,
    HK_SHAPE_TRIANGLE               = 3,
    HK_SHAPE_BOX                    = 4,
    HK_SHAPE_CAPSULE                = 5,
    HK_SHAPE_CONVEX_VERTICES        = 6,
    HK_SHAPE_COLLECTION             = 7,
    HK_SHAPE_BV_TREE                = 8,
    HK_SHAPE_LIST                   = 9,
    HK_SHAPE_MOPP                   = 10,
    HK_SHAPE_CONVEX_TRANSLATE       = 11,
    HK_SHAPE_CONVEX_TRANSFORM       = 12,
    HK_SHAPE_SAMPLED_HEIGHT_FIELD   = 13,
    HK_SHAPE_EXTENDED_MESH          = 14,
    HK_SHAPE_TRANSFORM              = 15,
    HK_SHAPE_MAX_ID_SPU             = 16,
    HK_SHAPE_CONVEX                 = 17,
    HK_SHAPE_PACKED_CONVEX_VERTICES = 18,
    HK_SHAPE_MOPP_EMBEDDED          = 19,
    HK_SHAPE_CONVEX_PIECE           = 20,
    HK_SHAPE_MULTI_SPHERE           = 21,
    HK_SHAPE_CONVEX_LIST            = 22,
    HK_SHAPE_TRIANGLE_COLLECTION    = 23,
    HK_SHAPE_MULTI_RAY              = 24,
    HK_SHAPE_HEIGHT_FIELD           = 25,
    HK_SHAPE_SPHERE_REP             = 26,
    HK_SHAPE_BV                     = 27,
    HK_SHAPE_PLANE                  = 28,
    HK_SHAPE_PHANTOM_CALLBACK       = 29,
    HK_SHAPE_USER0                  = 30,
    HK_SHAPE_USER1                  = 31,
    HK_SHAPE_USER2                  = 32,
    HK_SHAPE_MAX_ID                 = 33,
    HK_SHAPE_ALL                    = -1,
};
